### ISSUE TITLE
Use an oracle to profit from arbitrage

### ISSUE THREAD

**Issue by gonchs** [Uniswap/contracts-vyper#13] opened 2018-12-09 18:54 UTC
I love the idea of Uniswap and have been using it myself as a liquidity provider. However, at the moment, it seems that most of the profits are captured primarily by arbitrageurs.

The current state without an oracle:

1) There are 365.31 ETH and 34783.06 DAI in the contract, price to buy 1 ETH on Uniswap is 94.67
2) The market price of ETH moves to 110
3) Uniswap doesn't know this so the price to buy 1 ETH is still 94.67
4) Someone sees this, executes an arbitrage and brings the price on Uniswap up to 110
5) Liquidity providers have made only the 0.3% fee from the trading volume and nothing else, missing on an opportunity to sell at a higher price.

The scenario with a price oracle would be:

1) There are 365.31 ETH and 34783.06 DAI in the contract, price to buy 1 ETH on Uniswap is 94.67
2) The market price of ETH moves to 110
3) Uniswap knows this from a price oracle and limits the best possible buy price to at most 2% below the current market price, resulting in 107.8 (110*0.98) for 1 ETH.
4) This is still profitable for arbitrageurs so they still execute the trade and bring the price on Uniswap up to 110.
5) However, this time, liquidity providers have made a profit not only from the 0.3% fee but also from the cheaply acquired Ethereum sold at a higher price.

The only function of a price oracle would be to ensure that the best possible arbitrage offered by Uniswap is never more than 2% relative to the market price to allow liquidity providers to capture value from price movements. The rest of the contract would still work the same way. Aside from introducing a point of centralization with an oracle and potentially higher gas fees, are there any other downsides with this approach?

**Comment by Choicethoery** [comment] 2018-12-12 13:39
Using the MakerDAO oracles would be a good way to reduce the risks associated with centralization. 

The gas cost increase might be substantial. 

The incentive is there for liquidity providers to provide an accurate price so I'm not sure how much the possible arbitrage is so much the primary problem as much as simply increasing liquidity participants.

**Comment by gundas** [comment] 2019-01-10 10:38
@Choicethoery -  the problem is, that if only rational (arbitrage) traders are using the UniSwap, the UniSwap will always loose funds on any price movement. UniSwap can only work if there is enough "end user" trading who need the token exchange, but do not care  about  the price too much.
But in this case, one should wonder if the 0.3% fee is enough. The fee should depend on the price volatility of the assets traded (the higher volatility, the higher the fee) - one could take historical price movements of assets pair and simulate the losses from arbitrage, and decide what kind of fee would cover for those losses.

The only solution I could think to fix this is using an Oracle to set the price - it would be much cheaper than the services of  arbitrage traders.
I also created an alternative proposal for an Oracle - see issue #19

**Comment by gundas** [comment] 2019-01-10 10:41
> The incentive is there for liquidity providers to provide an accurate price so I'm not sure how much the possible arbitrage is so much the primary problem as much as simply increasing liquidity participants.

@Choicethoery - once the price ratio is set, the liquidity providers cannot change it. Every subsequent significant price move will incur loses for the liquidity providers. The only rational choice for the liquidity provider is to remove liquidity once the rate becomes incorrect or to do arbitraging himself (thus, taking  the assests from other co-providers on that contract).

**Comment by gundas** [comment] 2019-01-11 11:59
> @Choicethoery - once the price ratio is set, the liquidity providers cannot change it. Every subsequent significant price move will incur loses for the liquidity providers. The only rational choice for the liquidity provider is to remove liquidity once the rate becomes incorrect or to do arbitraging himself (thus, taking the assests from other co-providers on that contract).

Ok, was not correct in my statement above. If there is only one liquidity provider, to avoid losses he/she can adjust the price ratio by transferring directly Tokens or Ether (contract.kill(uniswap_contract) ) to the contract :)

**Comment by haydenadams** [comment] 2019-01-14 20:03
@gundas One thing I'm interested in setting up is a smart contract that allows a swaps + liquidity deposits to be made synchronously to allow liquidity providers to deposit liquidity at an exact specified rate.

**Comment by deacix** [comment] 2019-05-05 08:52
Centralization is no way!

**Closed** 2019-07-30 14:55 UTC
